<!DOCTYPE html>
<head>
  <meta charset="utf-8">
</head>

<body>
<form id="form">
</form>

<script>
// 1. Producer
// new Promise가 만들어질 때는 자동적으로 executor 함수가 실행됨
const promise = new Promise((resolve,reject) => {
    console.log('doing something...');
    setTimeout(() => {
        resolve('success'); // 성공
        // reject(new Error('fail')); // 실패
    },2000);
}); 

// 2. Consumers: then, catch, finally
promise
    .then(value => {
        console.log(value);
    })
    .catch(error => {
        console.log(error);
    })
    .finally(() => { // 성공, 실패 구분없이 무조건 실행
        console.log('finally');
    });

// 3. Promise chaining
const fetchNumber = new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
});

fetchNumber
.then(num => num * 2)
.then(num => num * 3)
.then(num => {
    return new Promise((resolve,reject) => {
        setTimeout(() => resolve(num -1), 1000);
    });
})
.then(num => console.log(num));

// 4.Error Handling
const getHen = () => new Promise((resolve, reject) => {
    setTimeout(resolve('🐔'), 1000);
});
const getEgg = hen => new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${hen} => 🐣`), 1000);
    //setTimeout(() => reject(new Error(`error! ${hen} => 🐣`)), 1000);
});
const cook = egg => new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => 🍡`), 1000);
});

getHen()
.then(getEgg) // .then(hen => getEgg(hen))
.then(cook) // .then(egg => cook(egg))
.then(console.log) //.then(meal => console.log(meal));
.catch(console.log); // 에러시 콘솔
</script>
</body>

